// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Answer struct {
	ID         int64
	Question   int64
	Answer     int64
	Submitdate string
}

type Question struct {
	ID       int64
	Category string
	Question string
	Picture  string
	Yes      int64
	No       int64
	Short    string
}
