// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const countAnswers = `-- name: CountAnswers :one
SELECT count(*) FROM answer
`

func (q *Queries) CountAnswers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAnswers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getQuestion = `-- name: GetQuestion :one
SELECT id, category, question, picture, short, yes, no
FROM question WHERE id = ?
`

type GetQuestionRow struct {
	ID       int64
	Category string
	Question string
	Picture  string
	Short    string
	Yes      int64
	No       int64
}

func (q *Queries) GetQuestion(ctx context.Context, id int64) (GetQuestionRow, error) {
	row := q.db.QueryRowContext(ctx, getQuestion, id)
	var i GetQuestionRow
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Question,
		&i.Picture,
		&i.Short,
		&i.Yes,
		&i.No,
	)
	return i, err
}

const getQuestionStats = `-- name: GetQuestionStats :one
SELECT short, yes, no FROM question WHERE id = ?
`

type GetQuestionStatsRow struct {
	Short string
	Yes   int64
	No    int64
}

func (q *Queries) GetQuestionStats(ctx context.Context, id int64) (GetQuestionStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getQuestionStats, id)
	var i GetQuestionStatsRow
	err := row.Scan(&i.Short, &i.Yes, &i.No)
	return i, err
}

const getRandomQuestion = `-- name: GetRandomQuestion :one
SELECT id, category, question, picture, short, yes, no
FROM question ORDER BY RANDOM() LIMIT 1
`

type GetRandomQuestionRow struct {
	ID       int64
	Category string
	Question string
	Picture  string
	Short    string
	Yes      int64
	No       int64
}

func (q *Queries) GetRandomQuestion(ctx context.Context) (GetRandomQuestionRow, error) {
	row := q.db.QueryRowContext(ctx, getRandomQuestion)
	var i GetRandomQuestionRow
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Question,
		&i.Picture,
		&i.Short,
		&i.Yes,
		&i.No,
	)
	return i, err
}

const incrementNo = `-- name: IncrementNo :exec
UPDATE question SET no = no + 1 WHERE id = ?
`

func (q *Queries) IncrementNo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementNo, id)
	return err
}

const incrementYes = `-- name: IncrementYes :exec
UPDATE question SET yes = yes + 1 WHERE id = ?
`

func (q *Queries) IncrementYes(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementYes, id)
	return err
}

const insertAnswer = `-- name: InsertAnswer :exec
INSERT INTO answer (question, answer, submitter, submitteragent)
VALUES (?, ?, ?, ?)
`

type InsertAnswerParams struct {
	Question       int64
	Answer         int64
	Submitter      string
	Submitteragent string
}

func (q *Queries) InsertAnswer(ctx context.Context, arg InsertAnswerParams) error {
	_, err := q.db.ExecContext(ctx, insertAnswer,
		arg.Question,
		arg.Answer,
		arg.Submitter,
		arg.Submitteragent,
	)
	return err
}
